config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  root 'pages#index'
  get 'pages/help'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  
  resources :users
  resources :topics
  resources :comments
  resources :articles

  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
  get 'comments/index'
  post '/comments', to: 'comments#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :user_id, presence: true
  # validates :description, presence: true
  validates :title, :video, :presence => true

  belongs_to :user
    
  mount_uploader :video, VideoUploader
    
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  
  has_many :comments
  has_many :comment_users, through: :comments, source: 'user'
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :topic
    validates :body, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true

  belongs_to :user

  mount_uploader :image, ImageUploader

  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  
  has_many :comments
  has_many :comment_users, through: :comments, source: 'user'
  
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length:{ maximum: 15 }
  validates :email, presence: true, format: { with: /[a-zA-Z0-9._+]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*/ }
  
  has_secure_password
  
  PW_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}\z/i
  validates :password, presence: true, format: { with: PW_REGEX }

  has_many :topics
  has_many :articles
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: 'topic'
  
  has_many :comments
  has_many :comments_topics, through: :comments, source: 'topic'
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger


  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
  
  
  helper_method :current_user, :logged_in?
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = current_user.articles.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "投稿が完了しました" }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "動画が削除されました" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :video)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new
      @comment = Comment.new
      @comment.topic_id = params[:topic_id]
      @comment.user_id = current_user.id
    end

  def create
        @comment = current_user.comments.new(comment_params)

        if @comment.save
            redirect_to topic_path, success: 'コメントを投稿しました'
        else
            flash.now[:danger] = 'コメント投稿に失敗しました'
            render :new
        end
  end
    
    private
    def comment_params
        params.require(:comment).permit( :user_id, :topic_id, :body)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_topics = current_user.favorite_topics
  end

  def create
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.topic_id = params[:topic_id]

    if favorite.save
      redirect_to topics_path, success: 'お気に入りに登録しました'
    else
      redirect_to topics_path, danger: 'お気に入りに登録に失敗しました'
    end
  end
  
  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, topic_id: params[:topic_id])
    favorite.destroy if favorite.present?

    if favorite.destroyed?
      redirect_to topics_path, success: 'お気に入りを解除しました'
    else
      redirect_to topics_path, danger: 'お気に入り解除に失敗しました'
    end
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def help
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to topics_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end
  
  
  private
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  def sessions_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all.includes(:favorite_users)
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = current_user.topics.new(topic_params)

    if @topic.save!
      redirect_to topics_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:image, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :video %>
    <%= form.file_field :video, :accept => 'video/*' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>動画を修正</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @articles.each do |article| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= article.user.name %>
            </h2>
              
              <%= video_tag article.video.url, autoplay: false, muted: false, controls: true , :size => "427x240"%>
                
                  
                   <%= article.title %>
                  <td><%= link_to '再生', article %></td>
                  <br><%= link_to '削除', article, method: :delete %>
                  <% end %>
              
          </div>
         </div>
      </div>
    </div>
</div>

app/views/articles/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">動画の投稿</h1>

            <%= form_with model: @article, local: true do |f| %>
            
            <div class="field">
              <%= f.label :video %>
              <%= f.file_field :video, :accept => 'video/*' %>
            </div>
            
         <div class="form-group">
              <%= f.label :title %>
              <%= f.text_area :title, class: 'form-control' %>
            </div>
       
            <% if logged_in? %>
            　<%= f.submit '投稿', class: 'btn btn-black btn-block' %>
            <% end %>
            
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      
      <td><%= @article.title %></td>

            <h2 style="topic-author">
              <div class="video-player">
                <%= video_tag @article.video.url, autoplay: false, muted: false, controls: true , :size => "854x480"%>
              </div>
            </h2>
            
            
             <%= link_to '削除する', @article, method: :delete %>
             <%= link_to 'Back', articles_path %>
             
             <% if @article.errors.any? %>
              <div class = "alert">
                <ul>
                  
                  <% user.errors.full_messages.each do |message| %>
                    <li><%= 失敗しました %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            
      
    </div>
  </div>
</div>      

app/views/comments/new.html.erb
<div class="comment-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">コメント投稿</h1>
        <%= form_for @comment do |f| %>
            <%= f.hidden_field :topic_id, value: @comment.topic_id %>
            <%= f.hidden_field :user_id, value: @comment.user_id %>
          
            <div class="form-group">
              <%= f.label :comment %>
              <%= f.text_area :body, class: 'form-control' %>
            </div>

              <% if logged_in? %>
                  <%= f.submit '投稿する', class: 'btn btn-black btn-block' %>
              <% end %>
          
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @favorite_topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            
             
             <% if %r[\.png|\.jpg|\.jpeg] =~ topic.image.filename %>
             <%= image_tag topic.image.url %>
             
             <% elsif %r[\.mp4|\.wmv|\.MOV] =~ topic.image.filename %>
             <%= video_tag topic.image.url, autoplay: false, muted: false, controls: true , :size => "427x240" %>
             
             <% end %>
            
            
            <% if topic.favorite_users.include?(current_user) %>
              <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                <%= image_tag 'icons/heart.png', class: 'topic-index-icon-red' %>
              <% end %>
            <% else %>
              <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>
              <% end %>
            <% end %>

           <%= topic.favorite_users.count %>

            <%= link_to new_comment_path(topic_id: topic.id) do %>
              <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <% end %>
            
            

            <p class="topic-text">
              <%= topic.description %>
            </p>
              <h5>&nbsp;comments</h5>
            <div id=<%= "comment_new#{topic.id}" %>></div>
              <p class="topic-text">
                <% topic.comments.each do |comment| %>
                  <p class="topic-text">
                  <%= comment.body %>
                  </p>
                <% end %>
              </p>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">画像の投稿</h1>
        
        <%= form_for @topic do |f| %>
        
          <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :image%>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>
          
          <% if logged_in? %>
            <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign up</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path, class: 'text-white' %>
      </div>
    </div>
  </div>
</div>